name: Build Presto UDFs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: checks
    container:
      image: public.ecr.aws/docker/library/maven:3.9.11-eclipse-temurin-24
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          mvn package
          cd target
          tar -czf udfs-3.0.1-SNAPSHOT.tar.gz udfs-3.0.1-SNAPSHOT/*
          tar -cf udfs-3.0.1-SNAPSHOT.tar udfs-3.0.1-SNAPSHOT/*

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: udfs-3.0.1-SNAPSHOT-jar
          path: target/udfs-3.0.1-SNAPSHOT.jar

      - name: Upload TAR.GZ artifact
        uses: actions/upload-artifact@v4
        with:
          name: udfs-3.0.1-SNAPSHOT-tar-gz
          path: target/udfs-3.0.1-SNAPSHOT.tar.gz

      - name: Upload TAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: udfs-3.0.1-SNAPSHOT-tar
          path: target/udfs-3.0.1-SNAPSHOT.tar

